### ISSUE TITLE
No Events from items on the Belt possible

### ISSUE THREAD

**Issue by geronimo078** [Theuntextured/AsynConveyorPlugin#4]
Not really a bug but it is currently not possible to generate events from items moving on the belt, because the mesh has no collision.
This would be very useful for taking items off the belt without to continuously check if something is there.

Suggestion is to wrap the mesh with an actor and that actor can be replaced via the conveyor_manager.
This allows to add custom functions, events or just the collision settings of the mesh to be adjusted.

But i can't say if this brings an advantage from a performance point of view. I think yes, if i imagine a large factory with thousands of devices constantly searching for items on the belt to take.

**Comment by Theuntextured** [comment]
I have an alternative. Have each conveyor remember what nodes are linked to it, so that when searching for items to extract, you can use a reference to a conveyor component to reduce the items to search for. Implementing it rn.

But about wrapping with an actor, imagine having thousands of items going around, this would mean thousands of actors, which will become extremely inefficient. Therefore I don't think that I will implement that. Also, collisions mean that the CPU needs to do more work, which I am trying to avoid.

**Comment by geronimo078** [comment]
The only thing to do is to try out which is the best option. But this is only possible with large factories. I can still adapt it to fit my game.

The only thing missing now is an option to build a sorter. Otherwise I like it very much.
